### ISSUE TITLE
Visibility when holding a key

### ISSUE THREAD

**Issue by zalteredbeastz** [gmastergreatee/ExternalCrosshairOverlay#11]
Hi, would it be possible to make the crosshair visible when holding a key ? If yes, maybe add an option to choose the key (keyboard or gamepad)?

**Comment by Kronzky** [comment]
Does this also work with mouse buttons? 
And if so, where do I configure this? I couldn't find any references to it, either in the GUI or in the code...

**Comment by gmastergreatee** [comment]
ECO doesn't support this currently.
This is a feature, which if implemented, will drastically increase the size of the app, therefore it seems to me as out of scope. Well who knows, maybe someday I/someone will be in need of this & would send a pull request.

I would suggest using Xpadder. In this, you could easily create a script which will help you map your "button" with the "=" key ("=" key toggles the visibility of crosshair in ECO).

**Comment by gmastergreatee** [comment]
Example of using XPadder

https://residentevilmodding.boards.net/thread/9949/crosshair-mod-visible-hud-turned
