### ISSUE TITLE
Even more Crosshair size scaling flexibility

### ISSUE THREAD

**Issue by laithalali** [gmastergreatee/ExternalCrosshairOverlay#12]
I would like to see a smaller scaling less than one or the ability so change the size of the image.

**Comment by laithalali** [comment]
Hi have you done it or you are working on it sorry new to github.

**Comment by gmastergreatee** [comment]
Will work on it

**Comment by gmastergreatee** [comment]
Completed https://github.com/gmastergreatee/ExternalCrosshairOverlay/commit/8dd1ac0565bbe4610295e9efcdfb5786f652f809
