### ISSUE TITLE
It seems that is not working in Fullscreen after update 1903 on w10

### ISSUE THREAD

**Issue by laithalali** [gmastergreatee/ExternalCrosshairOverlay#13]
It stopped working in fullscreen mode after the windows update.

**Comment by gmastergreatee** [comment]
1- Is it still not working?
2- Which game did you try it on?
3- Was the game in Fullscreen-Windowed mode?

**Comment by laithalali** [comment]
I used it in BF4 before that update and it worked fine but after the update it did not work in fullscreen anymore.
