### ISSUE TITLE
Cant Download

### ISSUE THREAD

**Issue by WongJiunnHann** [gmastergreatee/ExternalCrosshairOverlay#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by WongJiunnHann** [comment]
I am not a developer or anyone but i really wanted to download the .exe file which i manage to do so a couple days ago now the download link doenst work anymore.

**Comment by gmastergreatee** [comment]
I see! Thanks for informing bro, the last release was made 6 months ago, therefore the link expired.

Be sure to check the link again in 5 minutes from now. It should start working by then.

Thanks!
Have a great day!
