### ISSUE TITLE
No longer works after Sept 2019 windows update

### ISSUE THREAD

**Issue by WongJiunnHann** [gmastergreatee/ExternalCrosshairOverlay#15]
It wasnt working in Apex Legends however, by loading the crosshair onto Geforce Overlay (Nvidia) it works that is until the recent windows update. Thanks for the hardwork btw much appreciated.

**Comment by gmastergreatee** [comment]
What you are doing is actually a hack. ECO never had the capability to draw using DirectX/OpenGL(or Vulkan) directly into the process. All it does is draw a transparent window with width & height similar to the target process-window and containing the crosshair at its center.

**Comment by gmastergreatee** [comment]
Frankly windows 10 sucks, there's a lot Microsoft still needs to work on. Moreover it's full of bloatware. And some points to mention, the telemetry, random updates and spying code they implemented in it. :(
