### ISSUE TITLE
[Enhancement] Toggle Crosshair Visibility on Key-Input

### ISSUE THREAD

**Issue by clempe** [gmastergreatee/ExternalCrosshairOverlay#17]
I have a suggestions/enhancement.
Toggle or Change the visibility of the crosshair based on keyboard input. 

- Toggle visibility => e.g. when using the scope of a gun (Left Click)
- Hide/Show crosshair on specific input => e.g. when scoped in and then start running, the game automatically scopes out, therefore the crosshair should be invisible. (left shift)

**Comment by gmastergreatee** [comment]
Check #11

**Comment by gmastergreatee** [comment]
Check example [here](https://residentevilmodding.boards.net/thread/9949/crosshair-mod-visible-hud-turned)

**Comment by gmastergreatee** [comment]
Example of using XPadder

https://residentevilmodding.boards.net/thread/9949/crosshair-mod-visible-hud-turned
