### ISSUE TITLE
Hope that the size control can be input accurately

### ISSUE THREAD

**Issue by wyfang** [gmastergreatee/ExternalCrosshairOverlay#19]
For example, I made a 3*3 pixel center point picture myself, but the software seems to be difficult to control the size of the png icon correctly. It usually shows a bigger or smaller, unclear appearance, I hope it can be displayed on the screen in the original size of the picture.
![20200906121900](https://user-images.githubusercontent.com/17900420/92318183-2f912700-f03b-11ea-885b-f6dd86466422.png)

**Comment by wyfang** [comment]
And I have a bold idea. I found that this is very suitable for games without front sight, such as sniper rifle without sight. Therefore, if the software can recognize that the edge of the screen is black, it means that the sniper rifle has opened its sight. If it can temporarily make the front sight disappear, it will be very good and will not interfere with the game's own sight.

**Comment by gmastergreatee** [comment]
Related code fixes have been implemented, please test & report.

Other fixes include
- Scaling values will allow only 2 decimal places
- Clicking anywhere on the slider changes the scaling by 0.1 whereas moving arrow keys will change it by 0.01
- A scale of 10 will be equal to that of the image-size

Thank you very much
May you have a great day

**Comment by gmastergreatee** [comment]
As for the idea, please create a separate issue

**Comment by wyfang** [comment]
> 相关代码修复已实施，请测试并报告。
> 
> 其他修复包括
> 
> * 标度值仅允许小数点后2位
> * 单击滑块上的任意位置将缩放比例更改为0.1，而移动箭头键将其更改比例为0.01
> * 比例尺10等于图像尺寸的比例尺
> 
> 非常感谢你，
> 祝你有美好的一天



> Related code fixes have been implemented, please test & report.
> 
> Other fixes include
> 
> * Scaling values will allow only 2 decimal places
> * Clicking anywhere on the slider changes the scaling by 0.1 whereas moving arrow keys will change it by 0.01
> * A scale of 10 will be equal to that of the image-size
> 
> Thank you very much
> May you have a great day

It doesn't look like 10 is the original picture size. My test is as shown:
![20201015215442](https://user-images.githubusercontent.com/17900420/96139281-488dd180-0f31-11eb-8c29-2a7f53f9fad2.png)

**Comment by gmastergreatee** [comment]
@wyfang Is your DPI-scaling not 100% ?

![image](https://user-images.githubusercontent.com/17880848/96181109-1ab88500-0f51-11eb-9104-55a76f78d9bf.png)

Well my guess is that your DPI is different from 100%. In the following code, the only thing I did is just multiply the slider value with 0.1 

![image](https://user-images.githubusercontent.com/17880848/96180834-a8e03b80-0f50-11eb-8ce4-d27a30965d00.png)

**Comment by wyfang** [comment]
@gmastergreatee No, my system always uses 100% DPI, just like in your screenshot.

**Comment by gmastergreatee** [comment]
Hmm, that's strange then. Well, if you face any more problems, please create an issue.

Thank you
May you have a great day
