### ISSUE TITLE
More crosshair customization

### ISSUE THREAD

**Issue by ayy1lmao** [gmastergreatee/ExternalCrosshairOverlay#2]
Have a couple of presets ready to be picked and possibly a menu where you customize 100% of the crosshair

And really nice job doing this, really helped me a lot

**Comment by gmastergreatee** [comment]
Good to hear that it helped.
BTW, the first issue is exactly that(multiple inbuilt crosshair support) but now when you mention it, I'll add support for png/jpeg images too so that one could customize it even more.

**Comment by ayy1lmao** [comment]
its ok, you must be busy and stuff

very excited for 0.2, thank you for the amazing software

**Comment by gmastergreatee** [comment]
Closing this issue as #1 already tracks this feature
