### ISSUE TITLE
Adjust position?

### ISSUE THREAD

**Issue by StirliX** [gmastergreatee/ExternalCrosshairOverlay#3]
It works for my current old game - BioShock 2, even in fullscreen mode! I can see the crosshair but it's not where it needs to be =) Would be nice to be able to move it. with arrow keys for example?

**Comment by gmastergreatee** [comment]
ok, will add a system for setting that too. :)

**Comment by gmastergreatee** [comment]
Implementation details:-
- [ ] A global hotkey(possibly __Alt+F9__) for switching to __"Offset-Setup Mode"__
- [ ] Movement of the crosshair with the arrow keys
- [ ] Need to press hotkey again to switch back to normal mode(& possibly save the current offsets to the config file)

**Comment by gmastergreatee** [comment]
Completed https://github.com/gmastergreatee/ExternalCrosshairOverlay/commit/78a0d77de08d705fece40e509fe5e9ded164275f
