### ISSUE TITLE
Toggle visibility?

### ISSUE THREAD

**Issue by Battleroid** [gmastergreatee/ExternalCrosshairOverlay#5]
Would it be possible to add a keybind to toggle the visibility of the crosshair?

**Comment by gmastergreatee** [comment]
Oh ya! This seems a good feature. Will review and merge as soon as I reach home.
Thanks

Btw, sorry for the late reply. :smile:

**Comment by gmastergreatee** [comment]
I've merged the pull request but there is no indication of whether the crosshair is activated or hidden.
I think we may put this in the title, whenever the crosshair is hidden

Like "External Crosshair Overlay [Hidden]"

What do you say?

**Comment by Battleroid** [comment]
That seems alright.

**Comment by Artoria2e5** [comment]
Do you mind doing a build with this feature? It's been quite a while.

**Comment by gmastergreatee** [comment]
This feature has already been implemented, the only stuff that's left out is the status message indicator.

**Comment by Artoria2e5** [comment]
Well I mean... this feature, introduced in 1cfc765 (Dec 2018), is not in the latest downloadable release of 0.2.1 (Nov 2018).

**Comment by gmastergreatee** [comment]
Well the build with the last commit is already available at [appveyor](https://ci.appveyor.com/project/gmastergreatee/externalcrosshairoverlay/build/artifacts), so maybe I forgot to add it in the releases.

**Comment by Artoria2e5** [comment]
Thanks!
