### ISSUE TITLE
Your program turning on vert sync in game

### ISSUE THREAD

**Issue by TuTAH1** [gmastergreatee/ExternalCrosshairOverlay#9]
When I launch your program, select process and click "load", FPS downgrade to 60 and I get input lag (so probably vertical synchronization is turning on) Can you fix it?

**Comment by TuTAH1** [comment]
Hm it's more strange that it don't always happaning

**Comment by gmastergreatee** [comment]
May you please also mention your hardware specs & the __game__ you tried it on.

The program never binds(or injects) itself/anything-else into the game. What it does is refreshes the crosshair position again & again after an interval of 100 ms(which may be CPU intensive for some with low/mid spec hardware or while running multiple heavy applications).

**Comment by gmastergreatee** [comment]
May you please also test re-compiling the program after increasing the 100 millisecond timeout interval.

[This](https://github.com/gmastergreatee/ExternalCrosshairOverlay/blob/300fe54671eb07fec0a87a1014b48ea4101faacb/CrossHair_Overlay_Test/OverlayCrosshair.xaml.cs#L326) is the line.

For added info, this is what ECO does with game's UI :

![eco_flow](https://user-images.githubusercontent.com/17880848/52163743-8078c500-270c-11e9-93ad-1bc9e8dbbbf3.jpg)

**Comment by gmastergreatee** [comment]
:disappointed: sorry bro, I can't say anything before actually testing.
Just to confirm, you were using nVidia game overlay & bandicam for checking FPS, right?

**Comment by TuTAH1** [comment]
Rather **or** then **and**. And the first one is calling "Geforce Experience Overlay" if i know right

**Comment by gmastergreatee** [comment]
I have checked into this problem.

My findings are that FPS related issues occur because of the technology being used to develop this application, WPF in particular, as WPF was never actually designed with games in mind, therefore the default FPS is capped at 60.

I will do some more enhancements in the near future for better CPU optimization but I believe that won't affect FPS anyway.
